// Generated by Scripts/vendor-tree-sitter.py.
#ifndef C_TREE_SITTER_GRAMMARS_H
#define C_TREE_SITTER_GRAMMARS_H

// Each returns a `const TSLanguage *` (typed as `const void *` so this
// header does not depend on the runtime's).
const void *tree_sitter_bash(void);
const void *tree_sitter_c(void);
const void *tree_sitter_c_sharp(void);
const void *tree_sitter_cpp(void);
const void *tree_sitter_css(void);
const void *tree_sitter_dart(void);
const void *tree_sitter_diff(void);
const void *tree_sitter_dockerfile(void);
const void *tree_sitter_elixir(void);
const void *tree_sitter_fish(void);
const void *tree_sitter_go(void);
const void *tree_sitter_graphql(void);
const void *tree_sitter_haskell(void);
const void *tree_sitter_html(void);
const void *tree_sitter_java(void);
const void *tree_sitter_javascript(void);
const void *tree_sitter_json(void);
const void *tree_sitter_julia(void);
const void *tree_sitter_kotlin(void);
const void *tree_sitter_latex(void);
const void *tree_sitter_lua(void);
const void *tree_sitter_make(void);
const void *tree_sitter_objc(void);
const void *tree_sitter_php(void);
const void *tree_sitter_python(void);
const void *tree_sitter_r(void);
const void *tree_sitter_ruby(void);
const void *tree_sitter_rust(void);
const void *tree_sitter_scss(void);
const void *tree_sitter_swift(void);
const void *tree_sitter_toml(void);
const void *tree_sitter_typescript(void);
const void *tree_sitter_tsx(void);
const void *tree_sitter_xml(void);
const void *tree_sitter_yaml(void);
const void *tree_sitter_zig(void);

#endif
