/* Static-library equivalent of the CMake-generated export header. */
#ifndef CMARK_GFM_EXTENSIONS_EXPORT_H
#define CMARK_GFM_EXTENSIONS_EXPORT_H

#define CMARK_GFM_EXTENSIONS_EXPORT
#define CMARK_GFM_EXTENSIONS_NO_EXPORT

#ifndef CMARK_GFM_EXTENSIONS_DEPRECATED
#  define CMARK_GFM_EXTENSIONS_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef CMARK_GFM_EXTENSIONS_DEPRECATED_EXPORT
#  define CMARK_GFM_EXTENSIONS_DEPRECATED_EXPORT CMARK_GFM_EXTENSIONS_EXPORT CMARK_GFM_EXTENSIONS_DEPRECATED
#endif

#ifndef CMARK_GFM_EXTENSIONS_DEPRECATED_NO_EXPORT
#  define CMARK_GFM_EXTENSIONS_DEPRECATED_NO_EXPORT CMARK_GFM_EXTENSIONS_NO_EXPORT CMARK_GFM_EXTENSIONS_DEPRECATED
#endif

#endif /* CMARK_GFM_EXTENSIONS_EXPORT_H */
